import { Component } from '@angular/core';
import { ProductCardComponent } from '@components/product-card/product-card.component';
import { CardStatusEnum, Product, RarityEnum } from '@models/product.interface';

@Component({
  selector: 'app-restocks',
  imports: [ProductCardComponent],
  templateUrl: './restocks.component.html',
  styleUrl: './restocks.component.scss',
})
export class RestocksComponent {
  products: Product[] = [
    {
      id: 1,
      name: 'Sheoldred, The Apocalypse',
      price: 84.5,
      imageUrl: 'https://api.tcg.land/images/mtg/v2/dmu/107/en/a-75.webp',
      description: 'Sheoldred, The Apocalypse - Magic card',
      category: 'Dominaria United',
      status: 'available',
      rarity: RarityEnum.Mythic,
      releaseDate: new Date('2022-09-09'),
      stockQuantity: 10,
      createdAt: new Date(),
      updatedAt: new Date(),
      foil: false,
      cardStatus: CardStatusEnum.LightlyPlayed,
    },
    {
      id: 2,
      name: 'Ugin, The Spirit Dragon',
      price: 120.0,
      imageUrl: 'https://api.tcg.land/images/mtg/v2/ugin/1/en/a-75.webp',
      description: 'Ugin, The Spirit Dragon - Magic card',
      category: 'Core Set 2021',
      status: 'available',
      rarity: RarityEnum.Mythic,
      releaseDate: new Date('2020-07-03'),
      stockQuantity: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
      foil: true,
      cardStatus: CardStatusEnum.NearMint,
    },
    {
      id: 3,
      name: 'Charizard ex',
      price: 185.5,
      imageUrl: 'https://images.pokemontcg.io/sv3pt5/199_hires.png',
      description: 'Charizard ex - Pokémon TCG card',
      category: '151 (Scarlet & Violet)',
      status: 'available',
      rarity: RarityEnum.UltraRare,
      releaseDate: new Date('2023-09-22'),
      stockQuantity: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
      foil: true,
      cardStatus: CardStatusEnum.NearMint,
    },
    {
      id: 4,
      name: 'Mewtwo VSTAR',
      price: 95.0,
      imageUrl: 'https://api.tcg.land/images/pkm/v2/swsh12pt5gg/GG44/en/a-75.webp',
      description: 'Mewtwo VSTAR - Pokémon TCG card',
      category: 'Astral Radiance',
      status: 'available',
      rarity: RarityEnum.SecretRare,
      releaseDate: new Date('2022-05-27'),
      stockQuantity: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
      foil: true,
      cardStatus: CardStatusEnum.Mint,
    },
    {
      id: 5,
      name: 'Liliana of the Veil',
      price: 72.25,
      imageUrl: 'https://api.tcg.land/images/mtg/v2/pdmu/97p/en/a-75.webp',
      description: 'Liliana of the Veil - Magic card',
      category: 'Dominaria United',
      status: 'available',
      rarity: RarityEnum.Mythic,
      releaseDate: new Date('2022-09-09'),
      stockQuantity: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
      foil: false,
      cardStatus: CardStatusEnum.NearMint,
    },
    {
      id: 6,
      name: 'Pikachu Illustrator (Promo)',
      price: 250000.0,
      imageUrl: 'https://images.pokemontcg.io/basep/1_hires.png',
      description: 'Pikachu Illustrator Promo - Pokémon TCG card',
      category: 'Promo',
      status: 'available',
      rarity: RarityEnum.Promo,
      releaseDate: new Date('1998-01-01'),
      stockQuantity: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
      foil: true,
      cardStatus: CardStatusEnum.Excellent,
    },
  ];
}
