export enum ProductSectionType {
  BOOSTER_PACK = 'booster_pack',
  BOOSTER_BOX = 'booster_box',
  BOOSTER_BUNDLE = 'booster_bundle',
  ELITE_TRAINER_BOX = 'elite_trainer_box',
  ETB_POKEMON_CENTER = 'etb_pokemon_center',
  BUILD_BATTLE = 'build_battle',
  BUILD_BATTLE_STADIUM = 'build_battle_stadium',
  COLLECTION = 'collection',
  PREMIUM_COLLECTION = 'premium_collection',
  ULTRA_PREMIUM_COLLECTION = 'ultra_premium_collection',
  SPECIAL_COLLECTION = 'special_collection',
  BATTLE_DECK = 'battle_deck',
  LEAGUE_BATTLE_DECK = 'league_battle_deck',
  BLISTER_THREE_PACK = 'blister_three_pack',
  BLISTER_TWO_PACK = 'blister_two_pack',
  BLISTER_SINGLE_PACK = 'blister_single_pack',
}
