import { Injectable } from '@angular/core';
import { PlayerRanking } from '@models/player-ranking.interface';

@Injectable({
  providedIn: 'root',
})
export class RankingService {
  async getRanking(): Promise<PlayerRanking[]> {
    // mock temporal
    return [
      {
        id: 1,
        nickname: 'Yuya',
        game: 'POKEMON',
        points: 12,
        eventsPlayed: 1,
        wins: 3,
        losses: 0,
        draws: 0,
        position: 1,
        previousPosition: 2,
        avatarUrl: 'assets/avatares/yuya.png',
        tournaments: 1,
        winRate: 100,
      },
      {
        id: 2,
        nickname: 'Danilo',
        game: 'POKEMON',
        points: 64,
        eventsPlayed: 3,
        wins: 3,
        losses: 0,
        draws: 0,
        position: 2,
        previousPosition: 1,
        avatarUrl: 'assets/avatares/danilo.png',
        tournaments: 2,
        winRate: 100,
      },
      {
        id: 3,
        nickname: 'Aza',
        game: 'POKEMON',
        points: 40,
        eventsPlayed: 2,
        wins: 2,
        losses: 1,
        draws: 0,
        position: 3,
        previousPosition: 3,
        avatarUrl: 'assets/avatares/aza.png',
        tournaments: 2,
        winRate: 100,
      },
      {
        id: 4,
        nickname: 'Manu',
        game: 'POKEMON',
        points: 15,
        eventsPlayed: 1,
        wins: 2,
        losses: 1,
        draws: 0,
        position: 4,
        previousPosition: 6,
        avatarUrl: 'assets/avatares/manu.png',
        tournaments: 1,
        winRate: 100,
      },
      {
        id: 5,
        nickname: 'Gabo',
        game: 'POKEMON',
        points: 20,
        eventsPlayed: 1,
        wins: 2,
        losses: 1,
        draws: 0,
        position: 4,
        previousPosition: 4,
        avatarUrl: 'assets/avatares/gabo.png',
        tournaments: 1,
        winRate: 100,
      },
      {
        id: 6,
        nickname: 'Makoto',
        game: 'POKEMON',
        points: 61,
        eventsPlayed: 3,
        wins: 1,
        losses: 2,
        draws: 0,
        position: 6,
        previousPosition: 8,
        avatarUrl: 'assets/avatares/makoto.png',
        tournaments: 2,
        winRate: 100,
      },
      {
        id: 7,
        nickname: 'César',
        game: 'POKEMON',
        points: 40,
        eventsPlayed: 3,
        wins: 1,
        losses: 2,
        draws: 0,
        position: 7,
        previousPosition: 5,
        avatarUrl: 'assets/avatares/cesar.jpg',
        tournaments: 2,
        winRate: 100,
      },
      {
        id: 8,
        nickname: 'Richie',
        game: 'POKEMON',
        points: 3,
        eventsPlayed: 1,
        wins: 0,
        losses: 3,
        draws: 0,
        position: 8,
        previousPosition: 9,
        avatarUrl: 'assets/avatares/richie.png',
        tournaments: 1,
        winRate: 100,
      },
      {
        id: 9,
        nickname: 'Marquitos',
        game: 'POKEMON',
        points: 11,
        eventsPlayed: 1,
        wins: 0,
        losses: 1,
        draws: 0,
        position: 9,
        previousPosition: 7,
        avatarUrl: 'assets/avatares/marquitos.png',
        tournaments: 0,
        winRate: 100,
      },
      {
        id: 10,
        nickname: 'Yared',
        game: 'POKEMON',
        points: 16,
        eventsPlayed: 1,
        wins: 0,
        losses: 1,
        draws: 0,
        position: 10,
        previousPosition: 10,
        avatarUrl: 'assets/avatares/yare.png',
        tournaments: 0,
        winRate: 100,
      },
      {
        id: 11,
        nickname: 'Jordy',
        game: 'POKEMON',
        points: 2,
        eventsPlayed: 1,
        wins: 0,
        losses: 1,
        draws: 0,
        position: 10,
        previousPosition: 10,
        avatarUrl: 'assets/avatares/jordy.png',
        tournaments: 0,
        winRate: 100,
      },
      {
        id: 12,
        nickname: 'Panda',
        game: 'POKEMON',
        points: 49,
        eventsPlayed: 1,
        wins: 0,
        losses: 1,
        draws: 0,
        position: 10,
        previousPosition: 10,
        avatarUrl: 'assets/avatares/panda.jpg',
        tournaments: 1,
        winRate: 100,
      },
      {
        id: 13,
        nickname: 'Mateo',
        game: 'POKEMON',
        points: 23,
        eventsPlayed: 1,
        wins: 0,
        losses: 1,
        draws: 0,
        position: 10,
        previousPosition: 10,
        avatarUrl: 'assets/avatares/mateo.png',
        tournaments: 1,
        winRate: 100,
      },
      {
        id: 14,
        nickname: 'Pedro',
        game: 'POKEMON',
        points: 7,
        eventsPlayed: 1,
        wins: 0,
        losses: 1,
        draws: 0,
        position: 10,
        previousPosition: 10,
        avatarUrl: 'assets/avatares/pedro.png',
        tournaments: 1,
        winRate: 100,
      },
      {
        id: 15,
        nickname: 'Isis',
        game: 'POKEMON',
        points: 5,
        eventsPlayed: 1,
        wins: 0,
        losses: 4,
        draws: 0,
        position: 10,
        previousPosition: 10,
        avatarUrl: 'assets/avatares/isis.png',
        tournaments: 1,
        winRate: 100,
      },
      {
        id: 16,
        nickname: 'Andrés',
        game: 'POKEMON',
        points: 5,
        eventsPlayed: 0,
        wins: 0,
        losses: 1,
        draws: 0,
        position: 10,
        previousPosition: 10,
        avatarUrl: 'assets/avatares/andres.png',
        tournaments: 0,
        winRate: 100,
      },
    ];
  }
}
