import { Injectable } from '@angular/core';
import { PlayerRanking } from '@models/player-ranking.interface';

@Injectable({
  providedIn: 'root',
})
export class RankingService {
  async getRanking(game: string): Promise<PlayerRanking[]> {
    // mock temporal
    if (game === 'magic') {
      return [
        {
          id: 1,
          nickname: 'Osurox',
          game: 'MTG',
          points: 1,
          eventsPlayed: 1,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/osurox.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 2,
          nickname: 'Axl',
          game: 'MTG',
          points: 7,
          eventsPlayed: 2,
          wins: 1,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/axl.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 3,
          nickname: 'Jordi',
          game: 'MTG',
          points: 4,
          eventsPlayed: 2,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/jordi.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 4,
          nickname: 'Panda',
          game: 'MTG',
          points: 3,
          eventsPlayed: 1,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/panda.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 5,
          nickname: 'Lalo',
          game: 'MTG',
          points: 5,
          eventsPlayed: 1,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/lalo.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 6,
          nickname: 'Zenón',
          game: 'MTG',
          points: 6,
          eventsPlayed: 1,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/zenon.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 7,
          nickname: 'Julián',
          game: 'MTG',
          points: 2,
          eventsPlayed: 1,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/julian.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 8,
          nickname: 'Arturo',
          game: 'MTG',
          points: 3,
          eventsPlayed: 1,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/arturo.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 9,
          nickname: 'Diego',
          game: 'MTG',
          points: 1,
          eventsPlayed: 1,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/diego.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 10,
          nickname: 'Marquitos',
          game: 'MTG',
          points: 1,
          eventsPlayed: 1,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/marquitos.png',
          tournaments: 0,
          winRate: 0,
        },
      ];
    } else {
      return [
        {
          id: 1,
          nickname: 'Yuya',
          game: 'POKEMON',
          points: 18,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/yuya.png',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 2,
          nickname: 'Danilo',
          game: 'POKEMON',
          points: 17,
          eventsPlayed: 1,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/danilo.png',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 3,
          nickname: 'Aza',
          game: 'POKEMON',
          points: 14,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/aza.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 4,
          nickname: 'Manu',
          game: 'POKEMON',
          points: 10,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/manu.png',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 5,
          nickname: 'Gabo',
          game: 'POKEMON',
          points: 33,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/gabo.png',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 6,
          nickname: 'Makoto',
          game: 'POKEMON',
          points: 21,
          eventsPlayed: 1,
          wins: 1,
          losses: 1,
          draws: 1,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/makoto.png',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 7,
          nickname: 'César',
          game: 'POKEMON',
          points: 9,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/cesar.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 8,
          nickname: 'Richie',
          game: 'POKEMON',
          points: 0,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/richie.png',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 9,
          nickname: 'Marquitos',
          game: 'POKEMON',
          points: 5,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/marquitos.png',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 10,
          nickname: 'Yared',
          game: 'POKEMON',
          points: 0,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/yare.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 11,
          nickname: 'Jordy',
          game: 'POKEMON',
          points: 0,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/jordy.png',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 12,
          nickname: 'Panda',
          game: 'POKEMON',
          points: 15,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/panda.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 13,
          nickname: 'Mateo',
          game: 'POKEMON',
          points: 12,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/mateo.png',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 14,
          nickname: 'Pedro',
          game: 'POKEMON',
          points: 0,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/pedro.png',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 15,
          nickname: 'Isis',
          game: 'POKEMON',
          points: 0,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/isis.png',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 16,
          nickname: 'Andrés',
          game: 'POKEMON',
          points: 0,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/andres.png',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 17,
          nickname: 'Alex Pacher',
          game: 'POKEMON',
          points: 0,
          eventsPlayed: 0,
          wins: 0,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/alex_pacher.jpg',
          tournaments: 0,
          winRate: 0,
        },
        /* {
          id: 18,
          nickname: 'Marcos Jesus',
          game: 'POKEMON',
          points: 9,
          eventsPlayed: 1,
          wins: 3,
          losses: 0,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/marcos_jesus.jpg',
          tournaments: 0,
          winRate: 0,
        }, */
        /*  {
          id: 19,
          nickname: 'Alexis Giovanni',
          game: 'POKEMON',
          points: 6,
          eventsPlayed: 1,
          wins: 2,
          losses: 0,
          draws: 1,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/alexis_giovanni.jpg',
          tournaments: 0,
          winRate: 0,
        }, */
        {
          id: 20,
          nickname: 'Axl Paul',
          game: 'POKEMON',
          points: 4,
          eventsPlayed: 1,
          wins: 1,
          losses: 1,
          draws: 1,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/axl.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 21,
          nickname: 'Jorge',
          game: 'POKEMON',
          points: 5,
          eventsPlayed: 1,
          wins: 1,
          losses: 0,
          draws: 2,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/jorge.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 23,
          nickname: 'Javi',
          game: 'POKEMON',
          points: 1,
          eventsPlayed: 1,
          wins: 0,
          losses: 1,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/javi.jpg',
          tournaments: 0,
          winRate: 0,
        },
        {
          id: 24,
          nickname: 'Zenón',
          game: 'POKEMON',
          points: 6,
          eventsPlayed: 1,
          wins: 0,
          losses: 1,
          draws: 0,
          position: 0,
          previousPosition: 0,
          avatarUrl: 'assets/avatares/zenon.jpg',
          tournaments: 0,
          winRate: 0,
        },
      ];
    }
  }
}
