import { Injectable } from '@angular/core';
import { TcgEvent } from '@models/tournament.interface';

@Injectable({
  providedIn: 'root',
})
export class EventsService {
  async getEvents(): Promise<TcgEvent[]> {
    return [
      {
        id: 'evt-001',
        title: 'Magic: Noche de Commander',
        shortTitle: 'MAGIC',
        game: 'Magic: The Gathering',
        tier: 'LOCAL',
        date: new Date(2026, 1, 27),
        startTime: '18:00',
        format: 'COMMANDER',
        price: 0,
        currency: 'MXN',
        capacity: 40,
        registeredPlayers: 0,
        coverImageUrl: 'assets/posters/magic-commander.png',
        isActive: true,
        registrationOpen: false,
        location: 'Sucursal Centro',
      },
      {
        id: 'evt-002',
        title: 'Magic: Noche de Commander',
        shortTitle: 'MAGIC',
        game: 'Magic: The Gathering',
        tier: 'LOCAL',
        date: new Date(2026, 2, 6),
        startTime: '18:00',
        format: 'COMMANDER',
        price: 0,
        currency: 'MXN',
        capacity: 40,
        registeredPlayers: 0,
        coverImageUrl: 'assets/posters/magic-commander.png',
        isActive: true,
        registrationOpen: false,
        location: 'Sucursal Centro',
      },
      {
        id: 'evt-003',
        title: 'Pokémon Day - Viernes',
        shortTitle: 'POKÉMON',
        game: 'Pokémon TCG',
        tier: 'LOCAL',
        date: new Date(2026, 1, 27),
        startTime: '18:00',
        format: 'CASUAL',
        price: 0,
        currency: 'MXN',
        capacity: 50,
        registeredPlayers: 0,
        coverImageUrl: 'assets/posters/pokemon-day-viernes.jpg',
        isActive: true,
        registrationOpen: true,
        location: 'Sucursal Centro',
        description: 'Concurso de dibujo y Torneo de Pokémon Go',
        prizes: 'Boosters + Play Points',
      },
      {
        id: 'evt-004',
        title: 'Pokémon Day - Eventos Especiales',
        shortTitle: 'POKÉMON',
        game: 'Pokémon TCG',
        tier: 'LOCAL',
        date: new Date(2026, 1, 27),
        startTime: '14:00',
        format: 'STANDARD',
        price: 0,
        currency: 'MXN',
        capacity: 50,
        registeredPlayers: 0,
        coverImageUrl: 'assets/posters/pokemon-day.jpg',
        isActive: true,
        registrationOpen: true,
        location: 'Sucursal Centro',
        description: 'Eventos por el Pokémon Day',
        prizes: 'Boosters + Play Points',
      },
      {
        id: 'evt-005',
        title: 'Pokémon Day - Eventos Especiales',
        shortTitle: 'POKÉMON',
        game: 'Pokémon TCG',
        tier: 'LOCAL',
        date: new Date(2026, 1, 28),
        startTime: '14:00',
        format: 'STANDARD',
        price: 0,
        currency: 'MXN',
        capacity: 50,
        registeredPlayers: 0,
        coverImageUrl: 'assets/posters/pokemon-day.jpg',
        isActive: true,
        registrationOpen: true,
        location: 'Sucursal Centro',
        description: 'Eventos por el Pokémon Day',
        prizes: 'Boosters + Play Points',
      },
      {
        id: 'evt-006',
        title: 'Pokémon Day - Eventos Especiales',
        shortTitle: 'POKÉMON',
        game: 'Pokémon TCG',
        tier: 'LOCAL',
        date: new Date(2026, 2, 1),
        startTime: '17:00',
        format: 'STANDARD',
        price: 0,
        currency: 'MXN',
        capacity: 50,
        registeredPlayers: 0,
        coverImageUrl: 'assets/posters/pokemon-day.jpg',
        isActive: true,
        registrationOpen: true,
        location: 'Sucursal Centro',
        description: 'Eventos por el Pokémon Day',
        prizes: 'Boosters + Play Points',
      },
    ];
  }
}
